// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClosePostGameReducer from "../close_post_game_reducer";
import CreateLobbyReducer from "../create_lobby_reducer";
import EndMatchReducer from "../end_match_reducer";
import JoinLobbyReducer from "../join_lobby_reducer";
import LeaveLobbyReducer from "../leave_lobby_reducer";
import ResetLobbyReducer from "../reset_lobby_reducer";
import SetLobbySettingReducer from "../set_lobby_setting_reducer";
import StartMatchReducer from "../start_match_reducer";
import TugActivatePowerReducer from "../tug_activate_power_reducer";
import TugInitReducer from "../tug_init_reducer";
import TugRecordMissReducer from "../tug_record_miss_reducer";
import TugRpsCastVoteReducer from "../tug_rps_cast_vote_reducer";
import TugRpsContinueReducer from "../tug_rps_continue_reducer";
import TugSendWebrtcSignalReducer from "../tug_send_webrtc_signal_reducer";
import TugSetCameraEnabledReducer from "../tug_set_camera_enabled_reducer";
import TugSubmitReducer from "../tug_submit_reducer";
import TugTickReducer from "../tug_tick_reducer";

export type ClosePostGameParams = __Infer<typeof ClosePostGameReducer>;
export type CreateLobbyParams = __Infer<typeof CreateLobbyReducer>;
export type EndMatchParams = __Infer<typeof EndMatchReducer>;
export type JoinLobbyParams = __Infer<typeof JoinLobbyReducer>;
export type LeaveLobbyParams = __Infer<typeof LeaveLobbyReducer>;
export type ResetLobbyParams = __Infer<typeof ResetLobbyReducer>;
export type SetLobbySettingParams = __Infer<typeof SetLobbySettingReducer>;
export type StartMatchParams = __Infer<typeof StartMatchReducer>;
export type TugActivatePowerParams = __Infer<typeof TugActivatePowerReducer>;
export type TugInitParams = __Infer<typeof TugInitReducer>;
export type TugRecordMissParams = __Infer<typeof TugRecordMissReducer>;
export type TugRpsCastVoteParams = __Infer<typeof TugRpsCastVoteReducer>;
export type TugRpsContinueParams = __Infer<typeof TugRpsContinueReducer>;
export type TugSendWebrtcSignalParams = __Infer<typeof TugSendWebrtcSignalReducer>;
export type TugSetCameraEnabledParams = __Infer<typeof TugSetCameraEnabledReducer>;
export type TugSubmitParams = __Infer<typeof TugSubmitReducer>;
export type TugTickParams = __Infer<typeof TugTickReducer>;

