// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().primaryKey().name("event_id"),
  lobbyId: __t.string().name("lobby_id"),
  matchId: __t.string().name("match_id"),
  type: __t.string(),
  payloadJson: __t.string().name("payload_json"),
  at: __t.timestamp(),
});
