// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  lobbyId: __t.string().primaryKey().name("lobby_id"),
  joinCode: __t.string().name("join_code"),
  hostIdentity: __t.identity().name("host_identity"),
  status: __t.string(),
  gameType: __t.string().name("game_type"),
  activeMatchId: __t.string().name("active_match_id"),
  createdAt: __t.timestamp().name("created_at"),
});
