// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.string().primaryKey().name("match_id"),
  lobbyId: __t.string().name("lobby_id"),
  gameType: __t.string().name("game_type"),
  phase: __t.string(),
  startedAt: __t.timestamp().name("started_at"),
  endsAtMicros: __t.i64().name("ends_at_micros"),
  winnerTeam: __t.string().name("winner_team"),
  winnerPlayerId: __t.string().name("winner_player_id"),
  seed: __t.u32(),
});
