// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.string().primaryKey().name("player_id"),
  lobbyId: __t.string().name("lobby_id"),
  identity: __t.identity(),
  lobbyIdentityKey: __t.string().name("lobby_identity_key"),
  displayName: __t.string().name("display_name"),
  team: __t.string(),
  status: __t.string(),
  joinedAt: __t.timestamp().name("joined_at"),
  leftAtMicros: __t.i64().name("left_at_micros"),
  eliminatedReason: __t.string().name("eliminated_reason"),
});
