// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  tugPlayerStateId: __t.string().primaryKey().name("tug_player_state_id"),
  matchId: __t.string().name("match_id"),
  playerId: __t.string().name("player_id"),
  currentWord: __t.string().name("current_word"),
  correctCount: __t.i32().name("correct_count"),
  lastSubmitAtMicros: __t.i64().name("last_submit_at_micros"),
  deadlineAtMicros: __t.i64().name("deadline_at_micros"),
});
