// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.string().primaryKey().name("match_id"),
  roundNumber: __t.i32().name("round_number"),
  stage: __t.string(),
  votingEndsAtMicros: __t.i64().name("voting_ends_at_micros"),
  teamAChoice: __t.string().name("team_a_choice"),
  teamBChoice: __t.string().name("team_b_choice"),
  winnerTeam: __t.string().name("winner_team"),
  createdAtMicros: __t.i64().name("created_at_micros"),
});
