// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.string().primaryKey().name("match_id"),
  hostIdentity: __t.identity().name("host_identity"),
  score: __t.i32(),
  currentWord: __t.string().name("current_word"),
  wordVersion: __t.i32().name("word_version"),
  lastSubmitAtMicros: __t.i64().name("last_submit_at_micros"),
});
