// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.string().primaryKey().name("match_id"),
  ropePosition: __t.i32().name("rope_position"),
  winThreshold: __t.i32().name("win_threshold"),
  teamAForce: __t.i32().name("team_a_force"),
  teamBForce: __t.i32().name("team_b_force"),
  currentWord: __t.string().name("current_word"),
  wordVersion: __t.i32().name("word_version"),
  mode: __t.string(),
  wordMode: __t.string().name("word_mode"),
  rampTier: __t.i32().name("ramp_tier"),
  difficultyBonusTier: __t.i32().name("difficulty_bonus_tier"),
  activePowerId: __t.string().name("active_power_id"),
  powerExpiresAtMicros: __t.i64().name("power_expires_at_micros"),
  wordRotateMs: __t.i32().name("word_rotate_ms"),
  eliminationWordTimeMs: __t.i32().name("elimination_word_time_ms"),
  nextWordAtMicros: __t.i64().name("next_word_at_micros"),
  lastTickAtMicros: __t.i64().name("last_tick_at_micros"),
});
