// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  signalId: __t.string().primaryKey().name("signal_id"),
  matchId: __t.string().name("match_id"),
  streamEpoch: __t.i32().name("stream_epoch"),
  fromIdentity: __t.identity().name("from_identity"),
  toIdentity: __t.identity().name("to_identity"),
  kind: __t.string(),
  payloadJson: __t.string().name("payload_json"),
  createdAtMicros: __t.i64().name("created_at_micros"),
});
