// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameEvent = __t.object("GameEvent", {
  eventId: __t.string(),
  lobbyId: __t.string(),
  matchId: __t.string(),
  type: __t.string(),
  payloadJson: __t.string(),
  at: __t.timestamp(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const Lobby = __t.object("Lobby", {
  lobbyId: __t.string(),
  joinCode: __t.string(),
  hostIdentity: __t.identity(),
  status: __t.string(),
  gameType: __t.string(),
  activeMatchId: __t.string(),
  createdAt: __t.timestamp(),
});
export type Lobby = __Infer<typeof Lobby>;

export const LobbySettings = __t.object("LobbySettings", {
  settingId: __t.string(),
  lobbyId: __t.string(),
  key: __t.string(),
  valueJson: __t.string(),
});
export type LobbySettings = __Infer<typeof LobbySettings>;

export const Match = __t.object("Match", {
  matchId: __t.string(),
  lobbyId: __t.string(),
  gameType: __t.string(),
  phase: __t.string(),
  startedAt: __t.timestamp(),
  endsAtMicros: __t.i64(),
  winnerTeam: __t.string(),
  winnerPlayerId: __t.string(),
  seed: __t.u32(),
});
export type Match = __Infer<typeof Match>;

export const MatchClock = __t.object("MatchClock", {
  matchId: __t.string(),
  phaseEndsAt: __t.timestamp(),
  secondsRemaining: __t.i32(),
  tickRateMs: __t.i32(),
});
export type MatchClock = __Infer<typeof MatchClock>;

export const Player = __t.object("Player", {
  playerId: __t.string(),
  lobbyId: __t.string(),
  identity: __t.identity(),
  lobbyIdentityKey: __t.string(),
  displayName: __t.string(),
  team: __t.string(),
  status: __t.string(),
  joinedAt: __t.timestamp(),
  leftAtMicros: __t.i64(),
  eliminatedReason: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const Schedule = __t.object("Schedule", {
  scheduledId: __t.u64(),
  scheduleKey: __t.string(),
  matchId: __t.string(),
  kind: __t.string(),
  active: __t.bool(),
  scheduledAt: __t.scheduleAt(),
});
export type Schedule = __Infer<typeof Schedule>;

export const TugPlayerState = __t.object("TugPlayerState", {
  tugPlayerStateId: __t.string(),
  matchId: __t.string(),
  playerId: __t.string(),
  currentWord: __t.string(),
  correctCount: __t.i32(),
  lastSubmitAtMicros: __t.i64(),
  deadlineAtMicros: __t.i64(),
});
export type TugPlayerState = __Infer<typeof TugPlayerState>;

export const TugState = __t.object("TugState", {
  matchId: __t.string(),
  ropePosition: __t.i32(),
  winThreshold: __t.i32(),
  teamAForce: __t.i32(),
  teamBForce: __t.i32(),
  currentWord: __t.string(),
  wordVersion: __t.i32(),
  mode: __t.string(),
  wordRotateMs: __t.i32(),
  eliminationWordTimeMs: __t.i32(),
  nextWordAtMicros: __t.i64(),
  lastTickAtMicros: __t.i64(),
});
export type TugState = __Infer<typeof TugState>;

