import { WORD_MODE_NORMAL, WORD_MODE_SYMBOLS, WORD_MODE_TECH } from '../../core/constants';

export type WordMode = typeof WORD_MODE_NORMAL | typeof WORD_MODE_TECH | typeof WORD_MODE_SYMBOLS;

export type WordDifficultyTier = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export const MIN_WORD_DIFFICULTY_TIER: WordDifficultyTier = 1;
export const MAX_WORD_DIFFICULTY_TIER: WordDifficultyTier = 8;
export const WORD_DIFFICULTY_TIERS: readonly WordDifficultyTier[] = [1, 2, 3, 4, 5, 6, 7, 8];

export type WordType =
  | 'object'
  | 'action'
  | 'abstract'
  | 'nature'
  | 'command'
  | 'flag'
  | 'operator'
  | 'path_token'
  | 'brace_pattern'
  | 'pipe_pattern'
  | 'mixed_token';

export interface WordEntry {
  value: string;
  mode: WordMode;
  tier: WordDifficultyTier;
  type: WordType;
}

interface TierWordSource {
  object: readonly string[];
  action: readonly string[];
  abstract: readonly string[];
  nature: readonly string[];
}

interface TierTechSource {
  command: readonly string[];
  flag: readonly string[];
  operator: readonly string[];
  path_token: readonly string[];
}

interface TierSymbolsSource {
  brace_pattern: readonly string[];
  pipe_pattern: readonly string[];
  mixed_token: readonly string[];
}

const NORMAL_OBJECT_WORDS: readonly string[] = [
  'that',
  'this',
  'with',
  'from',
  'your',
  'have',
  'more',
  'will',
  'home',
  'about',
  'page',
  'search',
  'free',
  'other',
  'information',
  'time',
  'they',
  'site',
  'what',
  'which',
  'their',
  'news',
  'there',
  'only',
  'when',
  'contact',
  'here',
  'business',
  'also',
  'help',
  'view',
  'online',
  'first',
  'been',
  'would',
  'were',
  'services',
  'some',
  'these',
  'click',
  'like',
  'service',
  'than',
  'find',
  'price',
  'date',
  'back',
  'people',
  'list',
  'name',
  'just',
  'over',
  'state',
  'year',
  'into',
  'email',
  'health',
  'world',
  'next',
  'used',
  'work',
  'last',
  'most',
  'products',
  'music',
  'data',
  'make',
  'them',
  'should',
  'product',
  'system',
  'post',
  'city',
  'policy',
  'number',
  'such',
  'please',
  'available',
  'copyright',
  'support',
  'message',
  'after',
  'best',
  'software',
  'then',
  'good',
  'video',
  'well',
  'where',
  'info',
  'rights',
  'public',
  'books',
  'high',
  'school',
  'through',
  'each',
  'links',
  'review',
  'years',
  'order',
  'very',
  'privacy',
  'book',
  'items',
  'company',
  'read',
  'group',
  'need',
  'many',
  'user',
  'said',
  'does',
  'under',
  'general',
  'research',
  'university',
  'january',
  'mail',
  'full',
  'reviews',
  'program',
  'life',
  'know',
  'games',
  'days',
  'management',
  'part',
  'could',
  'great',
  'united',
  'hotel',
  'real',
  'item',
  'international',
  'center',
  'ebay',
  'must',
  'store',
  'travel',
  'comments',
  'made',
  'development',
  'report',
  'member',
  'details',
  'line',
  'terms',
  'before',
  'hotels',
  'send',
  'right',
  'type',
  'because',
  'local',
  'those',
  'using',
  'results',
  'office',
  'education',
  'national',
  'design',
  'take',
  'posted',
  'internet',
  'address',
  'community',
  'within',
  'states',
  'area',
  'want',
  'phone',
  'shipping',
  'reserved',
  'subject',
  'between',
  'forum',
  'family',
  'long',
  'based',
  'code',
  'show',
  'even',
  'black',
  'check',
  'special',
  'prices',
  'website',
  'index',
  'being',
  'women',
  'much',
  'sign',
  'file',
  'link',
  'open',
  'today',
  'technology',
  'south',
  'case',
  'project',
  'same',
  'pages',
  'version',
  'section',
  'found',
  'sports',
  'house',
  'related',
  'security',
  'both',
  'county',
  'american',
  'photo',
  'game',
  'members',
  'power',
  'while',
  'care',
  'network',
  'down',
  'computer',
  'systems',
  'three',
  'total',
  'place',
  'following',
  'download',
  'without',
  'access',
  'think',
  'north',
  'resources',
  'current',
  'posts',
  'media',
  'control',
  'water',
  'history',
  'pictures',
  'size',
  'personal',
  'since',
  'including',
  'guide',
  'shop',
  'directory',
  'board',
  'location',
  'change',
];

const NORMAL_ACTION_WORDS: readonly string[] = [
  'white',
  'text',
  'small',
  'rating',
  'rate',
  'government',
  'children',
  'during',
  'return',
  'students',
  'shopping',
  'account',
  'times',
  'sites',
  'level',
  'digital',
  'profile',
  'previous',
  'form',
  'events',
  'love',
  'john',
  'main',
  'call',
  'hours',
  'image',
  'department',
  'title',
  'description',
  'insurance',
  'another',
  'shall',
  'property',
  'class',
  'still',
  'money',
  'quality',
  'every',
  'listing',
  'content',
  'country',
  'private',
  'little',
  'visit',
  'save',
  'tools',
  'reply',
  'customer',
  'december',
  'compare',
  'movies',
  'include',
  'college',
  'value',
  'article',
  'york',
  'card',
  'jobs',
  'provide',
  'food',
  'source',
  'author',
  'different',
  'press',
  'learn',
  'sale',
  'around',
  'print',
  'course',
  'canada',
  'process',
  'teen',
  'room',
  'stock',
  'training',
  'credit',
  'point',
  'join',
  'science',
  'categories',
  'advanced',
  'west',
  'sales',
  'look',
  'english',
  'left',
  'team',
  'estate',
  'conditions',
  'select',
  'windows',
  'photos',
  'thread',
  'week',
  'category',
  'note',
  'live',
  'large',
  'gallery',
  'table',
  'register',
  'however',
  'june',
  'october',
  'november',
  'market',
  'library',
  'really',
  'action',
  'start',
  'series',
  'model',
  'features',
  'industry',
  'plan',
  'human',
  'provided',
  'required',
  'second',
  'accessories',
  'cost',
  'movie',
  'forums',
  'march',
  'september',
  'better',
  'questions',
  'july',
  'yahoo',
  'going',
  'medical',
  'test',
  'friend',
  'come',
  'server',
  'study',
  'application',
  'cart',
  'staff',
  'articles',
  'feedback',
  'again',
  'play',
  'looking',
  'issues',
  'april',
  'never',
  'users',
  'complete',
  'street',
  'topic',
  'comment',
  'financial',
  'things',
  'working',
  'against',
  'standard',
  'person',
  'below',
  'mobile',
  'less',
  'blog',
  'party',
  'payment',
  'equipment',
  'login',
  'student',
  'programs',
  'offers',
  'legal',
  'above',
  'recent',
  'park',
  'stores',
  'side',
  'problem',
  'give',
  'memory',
  'performance',
  'social',
  'august',
  'quote',
  'language',
  'story',
  'sell',
  'options',
  'experience',
  'rates',
  'create',
  'body',
  'young',
  'america',
  'important',
  'field',
  'east',
  'paper',
  'single',
  'activities',
  'club',
  'example',
  'girls',
  'additional',
  'password',
  'latest',
  'something',
  'road',
  'gift',
  'question',
  'changes',
  'night',
  'hard',
  'texas',
  'four',
  'poker',
  'status',
  'browse',
  'issue',
  'range',
  'building',
  'seller',
  'court',
  'february',
  'always',
  'result',
  'audio',
  'light',
  'write',
  'offer',
  'blue',
  'groups',
  'easy',
  'given',
  'files',
  'event',
  'release',
  'analysis',
  'request',
  'china',
  'making',
  'picture',
  'needs',
  'possible',
  'might',
  'professional',
  'month',
  'major',
  'star',
  'areas',
  'future',
  'space',
];

const NORMAL_ABSTRACT_WORDS: readonly string[] = [
  'committee',
  'hand',
  'cards',
  'problems',
  'london',
  'washington',
  'meeting',
  'become',
  'interest',
  'child',
  'keep',
  'enter',
  'california',
  'share',
  'similar',
  'garden',
  'schools',
  'million',
  'added',
  'reference',
  'companies',
  'listed',
  'baby',
  'learning',
  'energy',
  'delivery',
  'popular',
  'term',
  'film',
  'stories',
  'computers',
  'journal',
  'reports',
  'welcome',
  'central',
  'images',
  'president',
  'notice',
  'original',
  'head',
  'radio',
  'until',
  'cell',
  'color',
  'self',
  'council',
  'away',
  'includes',
  'track',
  'australia',
  'discussion',
  'archive',
  'once',
  'others',
  'entertainment',
  'agreement',
  'format',
  'least',
  'society',
  'months',
  'safety',
  'friends',
  'sure',
  'trade',
  'edition',
  'cars',
  'messages',
  'marketing',
  'tell',
  'further',
  'updated',
  'association',
  'able',
  'having',
  'provides',
  'david',
  'already',
  'green',
  'studies',
  'close',
  'common',
  'drive',
  'specific',
  'several',
  'gold',
  'living',
  'collection',
  'called',
  'short',
  'arts',
  'display',
  'limited',
  'powered',
  'solutions',
  'means',
  'director',
  'daily',
  'beach',
  'past',
  'natural',
  'whether',
  'electronics',
  'five',
  'upon',
  'period',
  'planning',
  'database',
  'says',
  'official',
  'weather',
  'land',
  'average',
  'done',
  'technical',
  'window',
  'france',
  'region',
  'island',
  'record',
  'direct',
  'microsoft',
  'conference',
  'environment',
  'records',
  'district',
  'calendar',
  'costs',
  'style',
  'front',
  'statement',
  'update',
  'parts',
  'ever',
  'downloads',
  'early',
  'miles',
  'sound',
  'resource',
  'present',
  'applications',
  'either',
  'document',
  'word',
  'works',
  'material',
  'bill',
  'written',
  'talk',
  'federal',
  'hosting',
  'rules',
  'final',
  'adult',
  'tickets',
  'thing',
  'centre',
  'requirements',
  'cheap',
  'nude',
  'kids',
  'finance',
  'true',
  'minutes',
  'else',
  'mark',
  'third',
  'rock',
  'gifts',
  'europe',
  'reading',
  'topics',
  'individual',
  'tips',
  'plus',
  'auto',
  'cover',
  'usually',
  'edit',
  'together',
  'videos',
  'percent',
  'fast',
  'function',
  'fact',
  'unit',
  'getting',
  'global',
  'tech',
  'meet',
  'economic',
  'player',
  'projects',
  'lyrics',
  'often',
  'subscribe',
  'submit',
  'germany',
  'amount',
  'watch',
  'included',
  'feel',
  'though',
  'bank',
  'risk',
  'thanks',
  'everything',
  'deals',
  'various',
  'words',
  'linux',
  'production',
  'commercial',
  'james',
  'weight',
  'town',
  'heart',
  'advertising',
  'received',
  'choose',
  'treatment',
  'newsletter',
  'archives',
  'points',
  'knowledge',
  'magazine',
  'error',
  'camera',
  'girl',
  'currently',
  'construction',
  'toys',
  'registered',
  'clear',
  'golf',
  'receive',
  'domain',
  'methods',
  'chapter',
  'makes',
  'protection',
  'policies',
  'loan',
  'wide',
  'beauty',
  'manager',
  'india',
  'position',
  'taken',
  'sort',
  'listings',
];

const NORMAL_NATURE_WORDS: readonly string[] = [
  'models',
  'michael',
  'known',
  'half',
  'cases',
  'step',
  'engineering',
  'florida',
  'simple',
  'quick',
  'none',
  'wireless',
  'license',
  'paul',
  'friday',
  'lake',
  'whole',
  'annual',
  'published',
  'later',
  'basic',
  'sony',
  'shows',
  'corporate',
  'google',
  'church',
  'method',
  'purchase',
  'customers',
  'active',
  'response',
  'practice',
  'hardware',
  'figure',
  'materials',
  'fire',
  'holiday',
  'chat',
  'enough',
  'designed',
  'along',
  'among',
  'death',
  'writing',
  'speed',
  'html',
  'countries',
  'loss',
  'face',
  'brand',
  'discount',
  'higher',
  'effects',
  'created',
  'remember',
  'standards',
  'yellow',
  'political',
  'increase',
  'advertise',
  'kingdom',
  'base',
  'near',
  'environmental',
  'thought',
  'stuff',
  'french',
  'storage',
  'japan',
  'doing',
  'loans',
  'shoes',
  'entry',
  'stay',
  'nature',
  'orders',
  'availability',
  'africa',
  'summary',
  'turn',
  'mean',
  'growth',
  'notes',
  'agency',
  'king',
  'monday',
  'european',
  'activity',
  'copy',
  'although',
  'drug',
  'pics',
  'western',
  'income',
  'force',
  'cash',
  'employment',
  'overall',
  'river',
  'commission',
  'package',
  'contents',
  'seen',
  'players',
  'engine',
  'port',
  'album',
  'regional',
  'stop',
  'supplies',
  'started',
  'administration',
  'institute',
  'views',
  'plans',
  'double',
  'build',
  'screen',
  'exchange',
  'types',
  'soon',
  'sponsored',
  'lines',
  'electronic',
  'continue',
  'across',
  'benefits',
  'needed',
  'season',
  'apply',
  'someone',
  'held',
  'anything',
  'printer',
  'condition',
  'effective',
  'believe',
  'organization',
  'effect',
  'asked',
  'mind',
  'sunday',
  'selection',
  'casino',
  'lost',
  'tour',
  'menu',
  'volume',
  'cross',
  'anyone',
  'mortgage',
  'hope',
  'silver',
  'corporation',
  'wish',
  'inside',
  'solution',
  'mature',
  'role',
  'rather',
  'weeks',
  'addition',
  'came',
  'supply',
  'nothing',
  'certain',
  'executive',
  'running',
  'lower',
  'necessary',
  'union',
  'jewelry',
  'according',
  'clothing',
  'particular',
  'fine',
  'names',
  'robert',
  'homepage',
  'hour',
  'bush',
  'islands',
  'advice',
  'career',
  'military',
  'rental',
  'decision',
  'leave',
  'british',
  'teens',
  'huge',
  'woman',
  'facilities',
  'kind',
  'sellers',
  'middle',
  'move',
  'cable',
  'opportunities',
  'taking',
  'values',
  'division',
  'coming',
  'tuesday',
  'object',
  'lesbian',
  'appropriate',
  'machine',
  'logo',
  'length',
  'actually',
  'nice',
  'score',
  'statistics',
  'client',
  'returns',
  'capital',
  'follow',
  'sample',
  'investment',
  'sent',
  'shown',
  'saturday',
  'christmas',
  'england',
  'culture',
  'band',
  'flash',
  'lead',
  'george',
  'choice',
  'went',
  'starting',
  'registration',
  'thursday',
  'courses',
  'consumer',
  'airport',
  'foreign',
  'artist',
  'outside',
  'furniture',
  'levels',
  'channel',
  'letter',
  'mode',
  'phones',
  'ideas',
  'wednesday',
  'structure',
];

const TECH_COMMAND_WORDS: readonly string[] = [
  'aa-enabled',
  'aa-exec',
  'aa-status',
  'aa-teardown',
  'accessdb',
  'add-shell',
  'addgnupghome',
  'addgroup',
  'addpart',
  'adduser',
  'agetty',
  'apport-bug',
  'apport-cli',
  'apport-collect',
  'apport-unpack',
  'appres',
  'apropos',
  'apt',
  'apt-cache',
  'apt-cdrom',
  'apt-config',
  'apt-ftparchive',
  'apt-get',
  'apt-key',
  'apt-mark',
  'apt-sortpkgs',
  'ar',
  'arch',
  'arpd',
  'arptables',
  'arptables-nft',
  'arptables-save',
  'as',
  'at',
  'atd',
  'atq',
  'atrm',
  'awk',
  'badblocks',
  'basename',
  'bash',
  'bashbug',
  'batch',
  'bc',
  'bdftopcf',
  'bdftruncate',
  'biosdecode',
  'blkdeactivate',
  'blkdiscard',
  'blkid',
  'blkzone',
  'blockdev',
  'boltctl',
  'bootctl',
  'bridge',
  'bsd-from',
  'bsd-write',
  'btrfs',
  'btrfs-convert',
  'btrfs-find-root',
  'btrfs-image',
  'btrfsck',
  'btrfstune',
  'bugpoint',
  'busctl',
  'busybox',
  'byobu',
  'byobu-config',
  'byobu-ctrl-a',
  'byobu-disable',
  'byobu-enable',
  'byobu-export',
  'byobu-janitor',
  'byobu-launch',
  'byobu-launcher',
  'byobu-layout',
  'byobu-prompt',
  'byobu-quiet',
  'byobu-screen',
  'byobu-shell',
  'byobu-silent',
  'byobu-status',
  'byobu-tmux',
  'byobu-ugraph',
  'byobu-ulevel',
  'bzcat',
  'bzcmp',
  'bzdiff',
  'bzegrep',
  'bzexe',
  'bzfgrep',
  'bzgrep',
  'bzless',
  'bzmore',
  'cal',
  'capsh',
  'captoinfo',
  'cat',
  'catchsegv',
  'catman',
  'cc',
  'cfdisk',
  'cgdisk',
  'chage',
  'chattr',
  'chcon',
  'chcpu',
  'chfn',
  'chgpasswd',
  'chgrp',
  'chmem',
  'chmod',
  'choom',
  'chown',
  'chpasswd',
  'chroot',
  'chrt',
  'chsh',
  'chvt',
  'ckbcomp',
  'cksum',
  'cloud-id',
  'cloud-init',
  'cloud-init-per',
  'cmp',
  'codepage',
  'col',
  'colcrt',
  'colrm',
  'column',
  'comm',
  'compose',
  'corelist',
  'corepack',
  'cp',
  'cpan',
  'cpgr',
  'cpio',
  'cpp',
  'cppw',
  'cron',
  'crontab',
  'cryptsetup',
  'csplit',
  'ctail',
  'ctrlaltdel',
  'ctstat',
  'curl',
  'cut',
  'cvtsudoers',
];

const TECH_FLAG_WORDS: readonly string[] = [
  '-cache?',
  '-cache!',
  '-cache+',
  '-cache=',
  '-cache~',
  '-buffer?',
  '-buffer!',
  '-buffer+',
  '-buffer=',
  '-buffer~',
  '-socket?',
  '-socket!',
  '-socket+',
  '-socket=',
  '-socket~',
  '-kernel?',
  '-kernel!',
  '-kernel+',
  '-kernel=',
  '-kernel~',
  '-daemon?',
  '-daemon!',
  '-daemon+',
  '-daemon=',
  '-daemon~',
  '-thread?',
  '-thread!',
  '-thread+',
  '-thread=',
  '-thread~',
  '-process?',
  '-process!',
  '-process+',
  '-process=',
  '-process~',
  '-runtime?',
  '-runtime!',
  '-runtime+',
  '-runtime=',
  '-runtime~',
  '-pipeline?',
  '-pipeline!',
  '-pipeline+',
  '-pipeline=',
  '-pipeline~',
  '-deploy?',
  '-deploy!',
  '-deploy+',
  '-deploy=',
  '-deploy~',
  '-staging?',
  '-staging!',
  '-staging+',
  '-staging=',
  '-staging~',
  '-monitor?',
  '-monitor!',
  '-monitor+',
  '-monitor=',
  '-monitor~',
  '-uptime?',
  '-uptime!',
  '-uptime+',
  '-uptime=',
  '-uptime~',
  '-latency?',
  '-latency!',
  '-latency+',
  '-latency=',
  '-latency~',
  '-throughput?',
  '-throughput!',
  '-throughput+',
  '-throughput=',
  '-throughput~',
  '-shard?',
  '-shard!',
  '-shard+',
  '-shard=',
  '-shard~',
  '-cluster?',
  '-cluster!',
  '-cluster+',
  '-cluster=',
  '-cluster~',
  '-replica?',
  '-replica!',
  '-replica+',
  '-replica=',
  '-replica~',
  '-gateway?',
  '-gateway!',
  '-gateway+',
  '-gateway=',
  '-gateway~',
  '-handler?',
  '-handler!',
  '-handler+',
  '-handler=',
  '-handler~',
  '-service?',
  '-service!',
  '-service+',
  '-service=',
  '-service~',
  '-ingress?',
  '-ingress!',
  '-ingress+',
  '-ingress=',
  '-ingress~',
  '-egress?',
  '-egress!',
  '-egress+',
  '-egress=',
  '-egress~',
  '-storage?',
  '-storage!',
  '-storage+',
  '-storage=',
  '-storage~',
  '-archive?',
  '-archive!',
  '-archive+',
  '-archive=',
  '-archive~',
  '-stream?',
  '-stream!',
  '-stream+',
  '-stream=',
  '-stream~',
  '-signal?',
  '-signal!',
  '-signal+',
  '-signal=',
  '-signal~',
  '-driver?',
  '-driver!',
  '-driver+',
  '-driver=',
  '-driver~',
  '-module?',
  '-module!',
  '-module+',
  '-module=',
  '-module~',
  '-packet?',
  '-packet!',
  '-packet+',
  '-packet=',
  '-packet~',
];

const TECH_OPERATOR_WORDS: readonly string[] = [
  'a+=a',
  'a-=a',
  'a*=a',
  'a==a',
  'a!=a',
  'a<=a',
  'a>=a',
  'a??a',
  'a::a',
  'a&&a',
  'a||a',
  'a~=a',
  'a=>a',
  'a<<a',
  'a>>a',
  'a+=b',
  'a-=b',
  'a*=b',
  'a==b',
  'a!=b',
  'a<=b',
  'a>=b',
  'a??b',
  'a::b',
  'a&&b',
  'a||b',
  'a~=b',
  'a=>b',
  'a<<b',
  'a>>b',
  'a+=c',
  'a-=c',
  'a*=c',
  'a==c',
  'a!=c',
  'a<=c',
  'a>=c',
  'a??c',
  'a::c',
  'a&&c',
  'a||c',
  'a~=c',
  'a=>c',
  'a<<c',
  'a>>c',
  'a+=d',
  'a-=d',
  'a*=d',
  'a==d',
  'a!=d',
  'a<=d',
  'a>=d',
  'a??d',
  'a::d',
  'a&&d',
  'a||d',
  'a~=d',
  'a=>d',
  'a<<d',
  'a>>d',
  'a+=e',
  'a-=e',
  'a*=e',
  'a==e',
  'a!=e',
  'a<=e',
  'a>=e',
  'a??e',
  'a::e',
  'a&&e',
  'a||e',
  'a~=e',
  'a=>e',
  'a<<e',
  'a>>e',
  'a+=f',
  'a-=f',
  'a*=f',
  'a==f',
  'a!=f',
  'a<=f',
  'a>=f',
  'a??f',
  'a::f',
  'a&&f',
  'a||f',
  'a~=f',
  'a=>f',
  'a<<f',
  'a>>f',
  'a+=g',
  'a-=g',
  'a*=g',
  'a==g',
  'a!=g',
  'a<=g',
  'a>=g',
  'a??g',
  'a::g',
  'a&&g',
  'a||g',
  'a~=g',
  'a=>g',
  'a<<g',
  'a>>g',
  'a+=h',
  'a-=h',
  'a*=h',
  'a==h',
  'a!=h',
  'a<=h',
  'a>=h',
  'a??h',
  'a::h',
  'a&&h',
  'a||h',
  'a~=h',
  'a=>h',
  'a<<h',
  'a>>h',
  'a+=i',
  'a-=i',
  'a*=i',
  'a==i',
  'a!=i',
  'a<=i',
  'a>=i',
  'a??i',
  'a::i',
  'a&&i',
  'a||i',
  'a~=i',
  'a=>i',
  'a<<i',
  'a>>i',
  'a+=j',
  'a-=j',
  'a*=j',
  'a==j',
  'a!=j',
  'a<=j',
  'a>=j',
  'a??j',
  'a::j',
  'a&&j',
  'a||j',
  'a~=j',
  'a=>j',
  'a<<j',
  'a>>j',
];

const TECH_PATH_TOKEN_WORDS: readonly string[] = [
  'cache/buffer',
  'cache/socket',
  'cache/kernel',
  'cache/daemon',
  'cache/thread',
  'cache/process',
  'cache/runtime',
  'cache/pipeline',
  'cache/deploy',
  'cache/staging',
  'cache/monitor',
  'cache/uptime',
  'cache/latency',
  'cache/shard',
  'cache/cluster',
  'cache/replica',
  'cache/gateway',
  'cache/handler',
  'cache/service',
  'cache/ingress',
  'cache/egress',
  'cache/storage',
  'cache/archive',
  'cache/stream',
  'cache/signal',
  'cache/driver',
  'cache/module',
  'cache/packet',
  'cache/schema',
  'cache/payload',
  'cache/vector',
  'cache/matrix',
  'cache/tensor',
  'cache/cipher',
  'cache/digest',
  'cache/token',
  'cache/session',
  'cache/auth',
  'cache/proxy',
  'cache/router',
  'cache/bridge',
  'cache/client',
  'cache/server',
  'cache/adapter',
  'cache/mapper',
  'cache/parser',
  'cache/renderer',
  'cache/compiler',
  'cache/linker',
  'cache/builder',
  'cache/tracker',
  'cache/logger',
  'cache/metrics',
  'cache/tracing',
  'cache/profiler',
  'cache/scanner',
  'cache/sandbox',
  'cache/rollback',
  'cache/rollout',
  'cache/feature',
  'cache/release',
  'cache/patcher',
  'cache/hotfix',
  'cache/version',
  'cache/branch',
  'cache/commit',
  'cache/merge',
  'cache/worker',
  'cache/queue',
  'cache/broker',
  'cache/topic',
  'cache/channel',
  'cache/backup',
  'cache/restore',
  'cache/snapshot',
  'cache/failover',
  'cache/watcher',
  'cache/reloader',
  'cache/cronjob',
  'cache/notifier',
  'cache/webhook',
  'cache/endpoint',
  'cache/request',
  'cache/response',
  'cache/timeout',
  'cache/retry',
  'cache/backoff',
  'cache/breaker',
  'cache/limiter',
  'cache/throttle',
  'cache/fairness',
  'cache/priority',
  'cache/deadline',
  'cache/handoff',
  'cache/syncer',
  'cache/muxer',
  'cache/demuxer',
  'cache/encoder',
  'cache/decoder',
  'cache/sampler',
  'cache/indexer',
  'cache/crawler',
  'cache/spider',
  'cache/manifest',
  'cache/artifact',
  'cache/registry',
  'cache/vault',
  'cache/secrets',
  'cache/policy',
  'cache/audit',
  'cache/runbook',
  'cache/playbook',
  'cache/beacon',
  'cache/watchdog',
  'cache/liveness',
  'cache/resizer',
  'cache/garbage',
  'cache/rewriter',
  'cache/minifier',
  'cache/bundler',
  'cache/linter',
  'cache/testcase',
  'cache/harness',
  'cache/fixture',
  'cache/mocking',
  'cache/stubber',
  'cache/fuzzer',
  'cache/mutator',
  'cache/aaexec',
  'cache/aastatus',
  'cache/accessdb',
  'cache/addshell',
  'cache/addgroup',
  'cache/addpart',
  'cache/adduser',
  'cache/agetty',
  'cache/appres',
  'cache/apropos',
  'cache/apt',
  'cache/aptcache',
  'cache/aptcdrom',
  'cache/aptget',
  'cache/aptkey',
  'cache/aptmark',
  'cache/arch',
  'cache/arpd',
  'cache/atd',
  'cache/atq',
  'cache/atrm',
  'cache/awk',
];

const SYMBOLS_BRACE_PATTERN_WORDS: readonly string[] = [
  '{a}',
  '[a]',
  '(a)',
  '<a>',
  '{[a]}',
  '[{a}]',
  '{b}',
  '[b]',
  '(b)',
  '<b>',
  '{[b]}',
  '[{b}]',
  '{c}',
  '[c]',
  '(c)',
  '<c>',
  '{[c]}',
  '[{c}]',
  '{d}',
  '[d]',
  '(d)',
  '<d>',
  '{[d]}',
  '[{d}]',
  '{e}',
  '[e]',
  '(e)',
  '<e>',
  '{[e]}',
  '[{e}]',
  '{f}',
  '[f]',
  '(f)',
  '<f>',
  '{[f]}',
  '[{f}]',
  '{g}',
  '[g]',
  '(g)',
  '<g>',
  '{[g]}',
  '[{g}]',
  '{h}',
  '[h]',
  '(h)',
  '<h>',
  '{[h]}',
  '[{h}]',
  '{i}',
  '[i]',
  '(i)',
  '<i>',
  '{[i]}',
  '[{i}]',
  '{j}',
  '[j]',
  '(j)',
  '<j>',
  '{[j]}',
  '[{j}]',
  '{k}',
  '[k]',
  '(k)',
  '<k>',
  '{[k]}',
  '[{k}]',
  '{l}',
  '[l]',
  '(l)',
  '<l>',
  '{[l]}',
  '[{l}]',
  '{m}',
  '[m]',
  '(m)',
  '<m>',
  '{[m]}',
  '[{m}]',
  '{n}',
  '[n]',
  '(n)',
  '<n>',
  '{[n]}',
  '[{n}]',
  '{o}',
  '[o]',
  '(o)',
  '<o>',
  '{[o]}',
  '[{o}]',
  '{p}',
  '[p]',
  '(p)',
  '<p>',
  '{[p]}',
  '[{p}]',
  '{q}',
  '[q]',
  '(q)',
  '<q>',
  '{[q]}',
  '[{q}]',
  '{r}',
  '[r]',
  '(r)',
  '<r>',
  '{[r]}',
  '[{r}]',
  '{s}',
  '[s]',
  '(s)',
  '<s>',
  '{[s]}',
  '[{s}]',
  '{t}',
  '[t]',
  '(t)',
  '<t>',
  '{[t]}',
  '[{t}]',
  '{u}',
  '[u]',
  '(u)',
  '<u>',
  '{[u]}',
  '[{u}]',
  '{v}',
  '[v]',
  '(v)',
  '<v>',
  '{[v]}',
  '[{v}]',
  '{w}',
  '[w]',
];

const SYMBOLS_PIPE_PATTERN_WORDS: readonly string[] = [
  '[a]=>[b]',
  '<a>|<b>',
  '({a})||({b})',
  '[a]&&[b]',
  '{a}=><b>',
  '<{a}>|(b)',
  '[b]=>[c]',
  '<b>|<c>',
  '({b})||({c})',
  '[b]&&[c]',
  '{b}=><c>',
  '<{b}>|(c)',
  '[c]=>[d]',
  '<c>|<d>',
  '({c})||({d})',
  '[c]&&[d]',
  '{c}=><d>',
  '<{c}>|(d)',
  '[d]=>[e]',
  '<d>|<e>',
  '({d})||({e})',
  '[d]&&[e]',
  '{d}=><e>',
  '<{d}>|(e)',
  '[e]=>[f]',
  '<e>|<f>',
  '({e})||({f})',
  '[e]&&[f]',
  '{e}=><f>',
  '<{e}>|(f)',
  '[f]=>[g]',
  '<f>|<g>',
  '({f})||({g})',
  '[f]&&[g]',
  '{f}=><g>',
  '<{f}>|(g)',
  '[g]=>[h]',
  '<g>|<h>',
  '({g})||({h})',
  '[g]&&[h]',
  '{g}=><h>',
  '<{g}>|(h)',
  '[h]=>[i]',
  '<h>|<i>',
  '({h})||({i})',
  '[h]&&[i]',
  '{h}=><i>',
  '<{h}>|(i)',
  '[i]=>[j]',
  '<i>|<j>',
  '({i})||({j})',
  '[i]&&[j]',
  '{i}=><j>',
  '<{i}>|(j)',
  '[j]=>[k]',
  '<j>|<k>',
  '({j})||({k})',
  '[j]&&[k]',
  '{j}=><k>',
  '<{j}>|(k)',
  '[k]=>[l]',
  '<k>|<l>',
  '({k})||({l})',
  '[k]&&[l]',
  '{k}=><l>',
  '<{k}>|(l)',
  '[l]=>[m]',
  '<l>|<m>',
  '({l})||({m})',
  '[l]&&[m]',
  '{l}=><m>',
  '<{l}>|(m)',
  '[m]=>[n]',
  '<m>|<n>',
  '({m})||({n})',
  '[m]&&[n]',
  '{m}=><n>',
  '<{m}>|(n)',
  '[n]=>[o]',
  '<n>|<o>',
  '({n})||({o})',
  '[n]&&[o]',
  '{n}=><o>',
  '<{n}>|(o)',
  '[o]=>[p]',
  '<o>|<p>',
  '({o})||({p})',
  '[o]&&[p]',
  '{o}=><p>',
  '<{o}>|(p)',
  '[p]=>[q]',
  '<p>|<q>',
  '({p})||({q})',
  '[p]&&[q]',
  '{p}=><q>',
  '<{p}>|(q)',
  '[q]=>[r]',
  '<q>|<r>',
  '({q})||({r})',
  '[q]&&[r]',
  '{q}=><r>',
  '<{q}>|(r)',
  '[r]=>[s]',
  '<r>|<s>',
  '({r})||({s})',
  '[r]&&[s]',
  '{r}=><s>',
  '<{r}>|(s)',
  '[s]=>[t]',
  '<s>|<t>',
  '({s})||({t})',
  '[s]&&[t]',
  '{s}=><t>',
  '<{s}>|(t)',
  '[t]=>[u]',
  '<t>|<u>',
  '({t})||({u})',
  '[t]&&[u]',
  '{t}=><u>',
  '<{t}>|(u)',
  '[u]=>[v]',
  '<u>|<v>',
  '({u})||({v})',
  '[u]&&[v]',
  '{u}=><v>',
  '<{u}>|(v)',
  '[v]=>[w]',
  '<v>|<w>',
  '({v})||({w})',
  '[v]&&[w]',
  '{v}=><w>',
  '<{v}>|(w)',
  '[w]=>[x]',
];

const SYMBOLS_MIXED_TOKEN_WORDS: readonly string[] = [
  '{a}+={b}',
  '<a>*=<b>',
  '{a}=={b}',
  '[a]!=[b]',
  '<a>&<b>',
  '({a})|({b})',
  '{a}~={b}',
  '[a]?=[b]',
  '({a})<<({b})',
  '[{a}]>>[{b}]',
  '{a}??{b}',
  '{b}+={c}',
  '<b>*=<c>',
  '{b}=={c}',
  '[b]!=[c]',
  '<b>&<c>',
  '({b})|({c})',
  '{b}~={c}',
  '[b]?=[c]',
  '({b})<<({c})',
  '[{b}]>>[{c}]',
  '{b}??{c}',
  '{c}+={d}',
  '<c>*=<d>',
  '{c}=={d}',
  '[c]!=[d]',
  '<c>&<d>',
  '({c})|({d})',
  '{c}~={d}',
  '[c]?=[d]',
  '({c})<<({d})',
  '[{c}]>>[{d}]',
  '{c}??{d}',
  '{d}+={e}',
  '<d>*=<e>',
  '{d}=={e}',
  '[d]!=[e]',
  '<d>&<e>',
  '({d})|({e})',
  '{d}~={e}',
  '[d]?=[e]',
  '({d})<<({e})',
  '[{d}]>>[{e}]',
  '{d}??{e}',
  '{e}+={f}',
  '<e>*=<f>',
  '{e}=={f}',
  '[e]!=[f]',
  '<e>&<f>',
  '({e})|({f})',
  '{e}~={f}',
  '[e]?=[f]',
  '({e})<<({f})',
  '[{e}]>>[{f}]',
  '{e}??{f}',
  '{f}+={g}',
  '<f>*=<g>',
  '{f}=={g}',
  '[f]!=[g]',
  '<f>&<g>',
  '({f})|({g})',
  '{f}~={g}',
  '[f]?=[g]',
  '({f})<<({g})',
  '[{f}]>>[{g}]',
  '{f}??{g}',
  '{g}+={h}',
  '<g>*=<h>',
  '{g}=={h}',
  '[g]!=[h]',
  '<g>&<h>',
  '({g})|({h})',
  '{g}~={h}',
  '[g]?=[h]',
  '({g})<<({h})',
  '[{g}]>>[{h}]',
  '{g}??{h}',
  '{h}+={i}',
  '<h>*=<i>',
  '{h}=={i}',
  '[h]!=[i]',
  '<h>&<i>',
  '({h})|({i})',
  '{h}~={i}',
  '[h]?=[i]',
  '({h})<<({i})',
  '[{h}]>>[{i}]',
  '{h}??{i}',
  '{i}+={j}',
  '<i>*=<j>',
  '{i}=={j}',
  '[i]!=[j]',
  '<i>&<j>',
  '({i})|({j})',
  '{i}~={j}',
  '[i]?=[j]',
  '({i})<<({j})',
  '[{i}]>>[{j}]',
  '{i}??{j}',
  '{j}+={k}',
  '<j>*=<k>',
  '{j}=={k}',
  '[j]!=[k]',
  '<j>&<k>',
  '({j})|({k})',
  '{j}~={k}',
  '[j]?=[k]',
  '({j})<<({k})',
  '[{j}]>>[{k}]',
  '{j}??{k}',
  '{k}+={l}',
  '<k>*=<l>',
  '{k}=={l}',
  '[k]!=[l]',
  '<k>&<l>',
  '({k})|({l})',
  '{k}~={l}',
  '[k]?=[l]',
  '({k})<<({l})',
  '[{k}]>>[{l}]',
  '{k}??{l}',
  '{l}+={m}',
  '<l>*=<m>',
  '{l}=={m}',
  '[l]!=[m]',
  '<l>&<m>',
  '({l})|({m})',
  '{l}~={m}',
  '[l]?=[m]',
  '({l})<<({m})',
  '[{l}]>>[{m}]',
  '{l}??{m}',
  '{m}+={n}',
];


function splitByTier(values: readonly string[], countsByTier: readonly number[]): Record<WordDifficultyTier, readonly string[]> {
  let offset = 0;
  const out = {} as Record<WordDifficultyTier, readonly string[]>;
  for (let index = 0; index < WORD_DIFFICULTY_TIERS.length; index += 1) {
    const tier = WORD_DIFFICULTY_TIERS[index];
    const count = countsByTier[index] ?? 0;
    out[tier] = values.slice(offset, offset + count);
    offset += count;
  }
  if (offset !== values.length) {
    throw new Error(`splitByTier consumed ${offset} of ${values.length} values`);
  }
  return out;
}

function countPattern(value: string, pattern: RegExp): number {
  return value.match(pattern)?.length ?? 0;
}

function scoreWordComplexity(mode: WordMode, value: string): number {
  const letters = value.match(/[a-z]/g) ?? [];
  const alphaCount = letters.length;
  const uniqueLetters = new Set(letters).size;
  const symbolCount = value.length - alphaCount;
  const connectorCount =
    countPattern(value, /->|=>|::|&&|\|\||<<|>>|\+=|-=|\*=|==|!=|<=|>=|\?\?|\?=|~=/g) +
    countPattern(value, /[{}\[\]()<>]/g);

  if (mode === WORD_MODE_NORMAL) {
    return value.length * 2 + uniqueLetters * 0.5;
  }

  if (mode === WORD_MODE_TECH) {
    return value.length * 1.6 + symbolCount * 2 + connectorCount * 1.4 + uniqueLetters * 0.2;
  }

  return value.length * 1.2 + symbolCount * 2.8 + connectorCount * 1.8 + uniqueLetters * 0.15;
}

function orderWordsByComplexity(mode: WordMode, values: readonly string[]): readonly string[] {
  return values
    .map((value, index) => ({ value, index, score: scoreWordComplexity(mode, value) }))
    .sort((a, b) => a.score - b.score || a.value.length - b.value.length || a.index - b.index)
    .map((row) => row.value);
}

const NORMAL_OBJECT_BY_TIER = splitByTier(
  orderWordsByComplexity(WORD_MODE_NORMAL, NORMAL_OBJECT_WORDS),
  [32, 31, 31, 31, 32, 31, 31, 31]
);
const NORMAL_ACTION_BY_TIER = splitByTier(
  orderWordsByComplexity(WORD_MODE_NORMAL, NORMAL_ACTION_WORDS),
  [31, 32, 31, 31, 31, 32, 31, 31]
);
const NORMAL_ABSTRACT_BY_TIER = splitByTier(
  orderWordsByComplexity(WORD_MODE_NORMAL, NORMAL_ABSTRACT_WORDS),
  [31, 31, 32, 31, 31, 31, 32, 31]
);
const NORMAL_NATURE_BY_TIER = splitByTier(
  orderWordsByComplexity(WORD_MODE_NORMAL, NORMAL_NATURE_WORDS),
  [31, 31, 31, 32, 31, 31, 31, 32]
);

const TECH_COMMAND_BY_TIER = splitByTier(
  orderWordsByComplexity(WORD_MODE_TECH, TECH_COMMAND_WORDS),
  [19, 19, 19, 18, 19, 19, 19, 18]
);
const TECH_FLAG_BY_TIER = splitByTier(
  orderWordsByComplexity(WORD_MODE_TECH, TECH_FLAG_WORDS),
  [19, 19, 18, 19, 19, 19, 18, 19]
);
const TECH_OPERATOR_BY_TIER = splitByTier(
  orderWordsByComplexity(WORD_MODE_TECH, TECH_OPERATOR_WORDS),
  [19, 18, 19, 19, 19, 18, 19, 19]
);
const TECH_PATH_TOKEN_BY_TIER = splitByTier(
  orderWordsByComplexity(WORD_MODE_TECH, TECH_PATH_TOKEN_WORDS),
  [18, 19, 19, 19, 18, 19, 19, 19]
);

const SYMBOLS_BRACE_PATTERN_BY_TIER = splitByTier(
  orderWordsByComplexity(WORD_MODE_SYMBOLS, SYMBOLS_BRACE_PATTERN_WORDS),
  [17, 17, 16, 17, 17, 16, 17, 17]
);
const SYMBOLS_PIPE_PATTERN_BY_TIER = splitByTier(
  orderWordsByComplexity(WORD_MODE_SYMBOLS, SYMBOLS_PIPE_PATTERN_WORDS),
  [17, 16, 17, 17, 16, 17, 17, 16]
);
const SYMBOLS_MIXED_TOKEN_BY_TIER = splitByTier(
  orderWordsByComplexity(WORD_MODE_SYMBOLS, SYMBOLS_MIXED_TOKEN_WORDS),
  [16, 17, 17, 16, 17, 17, 16, 17]
);

const NORMAL_TIER_WORDS: Record<WordDifficultyTier, TierWordSource> = {
  1: { object: NORMAL_OBJECT_BY_TIER[1], action: NORMAL_ACTION_BY_TIER[1], abstract: NORMAL_ABSTRACT_BY_TIER[1], nature: NORMAL_NATURE_BY_TIER[1] },
  2: { object: NORMAL_OBJECT_BY_TIER[2], action: NORMAL_ACTION_BY_TIER[2], abstract: NORMAL_ABSTRACT_BY_TIER[2], nature: NORMAL_NATURE_BY_TIER[2] },
  3: { object: NORMAL_OBJECT_BY_TIER[3], action: NORMAL_ACTION_BY_TIER[3], abstract: NORMAL_ABSTRACT_BY_TIER[3], nature: NORMAL_NATURE_BY_TIER[3] },
  4: { object: NORMAL_OBJECT_BY_TIER[4], action: NORMAL_ACTION_BY_TIER[4], abstract: NORMAL_ABSTRACT_BY_TIER[4], nature: NORMAL_NATURE_BY_TIER[4] },
  5: { object: NORMAL_OBJECT_BY_TIER[5], action: NORMAL_ACTION_BY_TIER[5], abstract: NORMAL_ABSTRACT_BY_TIER[5], nature: NORMAL_NATURE_BY_TIER[5] },
  6: { object: NORMAL_OBJECT_BY_TIER[6], action: NORMAL_ACTION_BY_TIER[6], abstract: NORMAL_ABSTRACT_BY_TIER[6], nature: NORMAL_NATURE_BY_TIER[6] },
  7: { object: NORMAL_OBJECT_BY_TIER[7], action: NORMAL_ACTION_BY_TIER[7], abstract: NORMAL_ABSTRACT_BY_TIER[7], nature: NORMAL_NATURE_BY_TIER[7] },
  8: { object: NORMAL_OBJECT_BY_TIER[8], action: NORMAL_ACTION_BY_TIER[8], abstract: NORMAL_ABSTRACT_BY_TIER[8], nature: NORMAL_NATURE_BY_TIER[8] },
};

const TECH_TIER_WORDS: Record<WordDifficultyTier, TierTechSource> = {
  1: { command: TECH_COMMAND_BY_TIER[1], flag: TECH_FLAG_BY_TIER[1], operator: TECH_OPERATOR_BY_TIER[1], path_token: TECH_PATH_TOKEN_BY_TIER[1] },
  2: { command: TECH_COMMAND_BY_TIER[2], flag: TECH_FLAG_BY_TIER[2], operator: TECH_OPERATOR_BY_TIER[2], path_token: TECH_PATH_TOKEN_BY_TIER[2] },
  3: { command: TECH_COMMAND_BY_TIER[3], flag: TECH_FLAG_BY_TIER[3], operator: TECH_OPERATOR_BY_TIER[3], path_token: TECH_PATH_TOKEN_BY_TIER[3] },
  4: { command: TECH_COMMAND_BY_TIER[4], flag: TECH_FLAG_BY_TIER[4], operator: TECH_OPERATOR_BY_TIER[4], path_token: TECH_PATH_TOKEN_BY_TIER[4] },
  5: { command: TECH_COMMAND_BY_TIER[5], flag: TECH_FLAG_BY_TIER[5], operator: TECH_OPERATOR_BY_TIER[5], path_token: TECH_PATH_TOKEN_BY_TIER[5] },
  6: { command: TECH_COMMAND_BY_TIER[6], flag: TECH_FLAG_BY_TIER[6], operator: TECH_OPERATOR_BY_TIER[6], path_token: TECH_PATH_TOKEN_BY_TIER[6] },
  7: { command: TECH_COMMAND_BY_TIER[7], flag: TECH_FLAG_BY_TIER[7], operator: TECH_OPERATOR_BY_TIER[7], path_token: TECH_PATH_TOKEN_BY_TIER[7] },
  8: { command: TECH_COMMAND_BY_TIER[8], flag: TECH_FLAG_BY_TIER[8], operator: TECH_OPERATOR_BY_TIER[8], path_token: TECH_PATH_TOKEN_BY_TIER[8] },
};

const SYMBOLS_TIER_WORDS: Record<WordDifficultyTier, TierSymbolsSource> = {
  1: { brace_pattern: SYMBOLS_BRACE_PATTERN_BY_TIER[1], pipe_pattern: SYMBOLS_PIPE_PATTERN_BY_TIER[1], mixed_token: SYMBOLS_MIXED_TOKEN_BY_TIER[1] },
  2: { brace_pattern: SYMBOLS_BRACE_PATTERN_BY_TIER[2], pipe_pattern: SYMBOLS_PIPE_PATTERN_BY_TIER[2], mixed_token: SYMBOLS_MIXED_TOKEN_BY_TIER[2] },
  3: { brace_pattern: SYMBOLS_BRACE_PATTERN_BY_TIER[3], pipe_pattern: SYMBOLS_PIPE_PATTERN_BY_TIER[3], mixed_token: SYMBOLS_MIXED_TOKEN_BY_TIER[3] },
  4: { brace_pattern: SYMBOLS_BRACE_PATTERN_BY_TIER[4], pipe_pattern: SYMBOLS_PIPE_PATTERN_BY_TIER[4], mixed_token: SYMBOLS_MIXED_TOKEN_BY_TIER[4] },
  5: { brace_pattern: SYMBOLS_BRACE_PATTERN_BY_TIER[5], pipe_pattern: SYMBOLS_PIPE_PATTERN_BY_TIER[5], mixed_token: SYMBOLS_MIXED_TOKEN_BY_TIER[5] },
  6: { brace_pattern: SYMBOLS_BRACE_PATTERN_BY_TIER[6], pipe_pattern: SYMBOLS_PIPE_PATTERN_BY_TIER[6], mixed_token: SYMBOLS_MIXED_TOKEN_BY_TIER[6] },
  7: { brace_pattern: SYMBOLS_BRACE_PATTERN_BY_TIER[7], pipe_pattern: SYMBOLS_PIPE_PATTERN_BY_TIER[7], mixed_token: SYMBOLS_MIXED_TOKEN_BY_TIER[7] },
  8: { brace_pattern: SYMBOLS_BRACE_PATTERN_BY_TIER[8], pipe_pattern: SYMBOLS_PIPE_PATTERN_BY_TIER[8], mixed_token: SYMBOLS_MIXED_TOKEN_BY_TIER[8] },
};

function addWordEntries(
  mode: WordMode,
  tier: WordDifficultyTier,
  type: WordType,
  values: readonly string[],
  target: WordEntry[]
): void {
  for (const value of values) {
    target.push({ value, mode, tier, type });
  }
}

function canonicalKey(value: string): string {
  return value.toLowerCase().replace(/[-_/:.]/g, '');
}

function validateCatalog(entries: readonly WordEntry[]): void {
  if (entries.length !== 2000) {
    throw new Error(`catalog size mismatch: expected 2000 got ${entries.length}`);
  }

  const normalPattern = /^[a-z]+$/;
  const techSymbolPattern = /^[a-z{}\[\]()<>+\-*/=!?&|:._~]+$/;

  const seenCanonical = new Set<string>();
  const modeCounts = new Map<WordMode, number>();
  const keyCounts = new Map<string, number>();

  for (const entry of entries) {
    modeCounts.set(entry.mode, (modeCounts.get(entry.mode) ?? 0) + 1);
    const compositeKey = `${entry.mode}:${entry.tier}:${entry.type}`;
    keyCounts.set(compositeKey, (keyCounts.get(compositeKey) ?? 0) + 1);

    if (entry.value !== entry.value.toLowerCase()) {
      throw new Error(`non-lowercase token: ${entry.value}`);
    }
    if (/\s/.test(entry.value)) {
      throw new Error(`token contains whitespace: ${entry.value}`);
    }
    if (/[0-9]/.test(entry.value)) {
      throw new Error(`token contains digit: ${entry.value}`);
    }
    if (/["'`]/.test(entry.value)) {
      throw new Error(`token contains quote/backtick: ${entry.value}`);
    }

    if (entry.mode === WORD_MODE_NORMAL) {
      if (entry.value.length > 14) {
        throw new Error(`normal token too long: ${entry.value}`);
      }
      if (!normalPattern.test(entry.value)) {
        throw new Error(`normal token invalid chars: ${entry.value}`);
      }
    } else {
      if (entry.value.length > 18) {
        throw new Error(`tech/symbol token too long: ${entry.value}`);
      }
      if (!techSymbolPattern.test(entry.value)) {
        throw new Error(`tech/symbol token invalid chars: ${entry.value}`);
      }
      if ((entry.value.match(/->/g)?.length ?? 0) > 1 || (entry.value.match(/=>/g)?.length ?? 0) > 1) {
        throw new Error(`arrow chain not allowed: ${entry.value}`);
      }
      if ((entry.value.match(/::/g)?.length ?? 0) > 1 || (entry.value.match(/&&/g)?.length ?? 0) > 1 || (entry.value.match(/\|\|/g)?.length ?? 0) > 1) {
        throw new Error(`connector chain not allowed: ${entry.value}`);
      }
    }

    const canonical = canonicalKey(entry.value);
    if (seenCanonical.has(canonical)) {
      throw new Error(`canonical duplicate detected: ${entry.value} => ${canonical}`);
    }
    seenCanonical.add(canonical);
  }

  if ((modeCounts.get(WORD_MODE_NORMAL) ?? 0) !== 1000) {
    throw new Error('normal mode count mismatch');
  }
  if ((modeCounts.get(WORD_MODE_TECH) ?? 0) !== 600) {
    throw new Error('tech mode count mismatch');
  }
  if ((modeCounts.get(WORD_MODE_SYMBOLS) ?? 0) !== 400) {
    throw new Error('symbols mode count mismatch');
  }

  const expected: Array<[WordMode, WordType, readonly number[]]> = [
    [WORD_MODE_NORMAL, 'object', [32, 31, 31, 31, 32, 31, 31, 31]],
    [WORD_MODE_NORMAL, 'action', [31, 32, 31, 31, 31, 32, 31, 31]],
    [WORD_MODE_NORMAL, 'abstract', [31, 31, 32, 31, 31, 31, 32, 31]],
    [WORD_MODE_NORMAL, 'nature', [31, 31, 31, 32, 31, 31, 31, 32]],
    [WORD_MODE_TECH, 'command', [19, 19, 19, 18, 19, 19, 19, 18]],
    [WORD_MODE_TECH, 'flag', [19, 19, 18, 19, 19, 19, 18, 19]],
    [WORD_MODE_TECH, 'operator', [19, 18, 19, 19, 19, 18, 19, 19]],
    [WORD_MODE_TECH, 'path_token', [18, 19, 19, 19, 18, 19, 19, 19]],
    [WORD_MODE_SYMBOLS, 'brace_pattern', [17, 17, 16, 17, 17, 16, 17, 17]],
    [WORD_MODE_SYMBOLS, 'pipe_pattern', [17, 16, 17, 17, 16, 17, 17, 16]],
    [WORD_MODE_SYMBOLS, 'mixed_token', [16, 17, 17, 16, 17, 17, 16, 17]],
  ];

  for (const [mode, type, tierCounts] of expected) {
    for (let index = 0; index < tierCounts.length; index += 1) {
      const tier = WORD_DIFFICULTY_TIERS[index];
      const key = `${mode}:${tier}:${type}`;
      const got = keyCounts.get(key) ?? 0;
      const want = tierCounts[index];
      if (got !== want) {
        throw new Error(`quota mismatch for ${key} expected ${want} got ${got}`);
      }
    }
  }
}

function buildCatalog(): WordEntry[] {
  const entries: WordEntry[] = [];

  for (const tier of WORD_DIFFICULTY_TIERS) {
    const normal = NORMAL_TIER_WORDS[tier];
    addWordEntries(WORD_MODE_NORMAL, tier, 'object', normal.object, entries);
    addWordEntries(WORD_MODE_NORMAL, tier, 'action', normal.action, entries);
    addWordEntries(WORD_MODE_NORMAL, tier, 'abstract', normal.abstract, entries);
    addWordEntries(WORD_MODE_NORMAL, tier, 'nature', normal.nature, entries);

    const tech = TECH_TIER_WORDS[tier];
    addWordEntries(WORD_MODE_TECH, tier, 'command', tech.command, entries);
    addWordEntries(WORD_MODE_TECH, tier, 'flag', tech.flag, entries);
    addWordEntries(WORD_MODE_TECH, tier, 'operator', tech.operator, entries);
    addWordEntries(WORD_MODE_TECH, tier, 'path_token', tech.path_token, entries);

    const symbols = SYMBOLS_TIER_WORDS[tier];
    addWordEntries(WORD_MODE_SYMBOLS, tier, 'brace_pattern', symbols.brace_pattern, entries);
    addWordEntries(WORD_MODE_SYMBOLS, tier, 'pipe_pattern', symbols.pipe_pattern, entries);
    addWordEntries(WORD_MODE_SYMBOLS, tier, 'mixed_token', symbols.mixed_token, entries);
  }

  validateCatalog(entries);
  return entries;
}

export const WORD_CATALOG: readonly WordEntry[] = Object.freeze(buildCatalog());

export function countCatalogEntriesByMode(mode: WordMode): number {
  let total = 0;
  for (const entry of WORD_CATALOG) {
    if (entry.mode === mode) {
      total += 1;
    }
  }
  return total;
}
